### ISSUE TITLE
onMounted in Vue 2 Composition API

### ISSUE THREAD

**Issue by leereichardt** [ariesjia/vue-composition-test-utils#5]
I'm trying to test a function and it's got an onMounted call inside. When running the test, I'm getting the following error:

`    [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup().`

Test code is as follow
```
// @ts-ignore
const wrapper  = mountComposition(useFooterSettings({ itemHasClosed: false }));
```

Please note, I had to add the ts-ignore as I had to pass a parameter to the method, but the type definitions didn't like this?

Any help would be greatly appreciated.

**Comment by ariesjia** [comment]
Hello

compositio function shuold be callback , then  `mountComposition ` can call it in vue `stepup` function 
You can try like this
```
// @ts-ignore
const wrapper  = mountComposition(() => useFooterSettings({ itemHasClosed: false }));
```

thanks :)
